- name: add repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.4/debian stable main' state=present
  sudo: yes

- name: install
  apt: pkg=logstash update_cache=yes force=yes
  sudo: yes

- name: restart logstash
  service: name=logstash state=restarted enabled=yes
  sudo: yes
